# Registers a Windows Task Scheduler job that runs the minute-check every 1 minute,
# HIDDEN (no console window pop-up).
# Run from PowerShell:  powershell -ExecutionPolicy Bypass -File scripts/setup_task.ps1
# Re-run after moving the repo. Remove with: Unregister-ScheduledTask -TaskName "RemindMeMinuteCheck"

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path "$PSScriptRoot\..").Path
$Uv = (Get-Command uv).Source
$TaskName = "RemindMeMinuteCheck"
$Launcher = Join-Path $PSScriptRoot "run_hidden.vbs"

# Generate a hidden launcher (wscript + window style 0 = no console window).
# Machine-specific paths -> this file is gitignored.
@"
' Auto-generated by setup_task.ps1 - launches the minute-check without a window.
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "$RepoRoot"
shell.Run """$Uv"" run --project ""$RepoRoot"" src\main.py", 0, False
"@ | Set-Content -Path $Launcher -Encoding ASCII

$Action = New-ScheduledTaskAction `
    -Execute "wscript.exe" `
    -Argument """$Launcher""" `
    -WorkingDirectory $RepoRoot

# Every 1 minute, indefinitely.
$Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) `
    -RepetitionInterval (New-TimeSpan -Minutes 1)

$Settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 2)

Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger `
    -Settings $Settings -Description "GCal -> Twilio 1-minute meeting call reminders (hidden)" -Force

Write-Host "Task '$TaskName' registered (every 1 min, HIDDEN). Repo: $RepoRoot"
Write-Host "Test now with:  Start-ScheduledTask -TaskName '$TaskName'  (no window should appear)"
Write-Host "NOTE: the PC must be awake for calls to fire."
